# Generated by Django 5.2.1 on 2025-06-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('datetime', models.TextField()),
                ('reason', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
