name: CI/CD - Build, Test, and Deploy MERN Stack

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-test:
    name: Build and Test Frontend & Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install and test backend
      - name: Install Backend Dependencies
        working-directory: ./code/backend
        run: npm install

      - name: Test Backend
        working-directory: ./code/backend
        run: |
          if npm run test; then
            echo "Backend tests passed"
          else
            echo "Backend tests failed"
            exit 1
          fi

      # Install, build, and test frontend
      - name: Install Frontend Dependencies
        working-directory: ./code/frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./code/frontend
        run: npm run build

      - name: Test Frontend
        working-directory: ./code/frontend
        run: |
          if npm run test; then
            echo "Frontend tests passed"
          else
            echo "Frontend tests failed"
            exit 1
          fi

  deploy-backend:
  
    name: Deploy Backend to Heroku
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
     
        
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Heroku CLI
        uses: extractions/setup-heroku@v1

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mymagicalbedtime" 
          heroku_email: "hong.zhang94@gmail.com" 
          appdir: "code/backend" # Deploy only the backend directory
